### PR TITLE
Issue 26

### PR DESCRIPTION
**Pull request by oxhead**
The data commands that invoke save/restore functions on the service node.

### CODE REVIEW

**Comment by vin0110** [comment]
Does this contain the changes you made yesterday?

**Comment by oxhead** [comment]
The changes made yesterday are committed to another repo, which will be merged later into haas.

**Comment by vin0110** [comment]
So do you want we to ignore this PR or merge it?

**Comment by oxhead** [comment]
We need to merge this one first.  Other changes will be merged later in #30

**Pull request merged**
